## `Numpy Array` v/s `Python List`

In [6]:
# speed in list
a = [i for i in range(10000000)]
b = [i for i in range(10000000, 20000000)]
c = []

import time
start = time.time()
for i in range(len(a)):
    c.append(a[i] + b[i])
print(time.time() - start)



6.013935565948486


In [ ]:
import numpy as np
a = np.arange(10000000)
b = np.arange(10000000, 20000000)

start = time.time()
c = a+b
print(time.time() - start)

0.5254020690917969


In [22]:
# memory of list
a = [i for i in range(10000000)]
b = np.arange(10000000)

import sys
print(f'Size of list: {sys.getsizeof(a)} bytes')
print(f'Size of array: {sys.getsizeof(b)} bytes')

Size of list: 89095160 bytes
Size of array: 40000112 bytes


## `Advanced Indexing`

In [25]:
a = np.arange(30, 46).reshape(4,4)
a

array([[30, 31, 32, 33],
       [34, 35, 36, 37],
       [38, 39, 40, 41],
       [42, 43, 44, 45]])

In [ ]:
# fancy indexing
# example: we need the 1st, 3rd and the 4th row (no pattern)
a[[0, 2, 3]]


array([[30, 31, 32, 33],
       [38, 39, 40, 41],
       [42, 43, 44, 45]])

In [27]:
a[:,[1,2]]

array([[31, 32],
       [35, 36],
       [39, 40],
       [43, 44]])

In [29]:
# Boolean indexing
a = np.random.randint(1, 200, 30).reshape(6,5)

In [40]:
#find numbers grater that 60
a[a>60]

array([115, 180, 122, 102,  98,  73, 144, 121, 176,  71, 198, 192, 113,
       133, 115, 129, 152,  75, 140, 181,  67])

In [41]:
#find all the even numbers
a[a%2 == 0]

array([ 30, 180, 122, 102,  98, 144, 176, 198,  32, 192, 152, 140])

In [42]:
# find numbers greater than 60 and also even
a[(a%2 == 0) & (a>60)]

array([180, 122, 102,  98, 144, 176, 198, 192, 152, 140])

In [43]:
# numbers divisable by 5
a[a%5 == 0]


array([ 30, 115, 180, 115,  25,  75, 140])

In [44]:
# numbers not divisable by 5
a[~(a%5 == 0)]


array([ 43, 122, 102,  98,  73, 144, 121,  21, 176,  49,  71,  57, 198,
        33,  32, 192, 113, 133, 129,  27, 152, 181,  67])

## `Broadcasting`
- Broadcasting in NumPy is a feature that allows arrays of different shapes to be used together in arithmetic operations without explicitly reshaping them.

    ### `Rules`
    *1. Array Dimensions must be equal:*
        
    - If they are not equal, the smaller dimension array is broadcasted by new dimension with size 1 to match the larger one.

    *2. Size of each dimension must be equal:*
    - If they are not equal, dimensions with size 1 are streched to match the size of the larger array.
    - If there is no dimension with size 1, the arrays are not broadcastable.


In [47]:
a = np.arange(12).reshape(4,3)
b = np.arange(3)

print(a)
print(b)
print(a+b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [49]:
a = np.arange(12).reshape(3,4)
b = np.arange(3)

print(a)
print(b)
print(a+b) # error

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2]


ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [50]:
a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)

print(a)
print(b)
print(a+b)

[[0 1 2]]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [53]:
a = np.arange(4).reshape(1,4)
b = np.arange(3).reshape(3,1)

print(a)
print(b)
print(a+b)

[[0 1 2 3]]
[[0]
 [1]
 [2]]
[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]]


In [54]:
a = np.arange(4).reshape(3,4)
b = np.arange(3).reshape(4,3)

print(a)
print(b)
print(a+b)

ValueError: cannot reshape array of size 4 into shape (3,4)