## `Fundamentals of Numpy Arrays`

In [1]:
import numpy as np

### `Basic Functions`

In [ ]:
#creating numpy arrays
# 1D array / vector
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
#2D array / matrix
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# 3D array / tensor
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) 
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [12]:
# dtype
d = np.array([1, 2, 3, 4, 5], dtype = float)
d

array([1., 2., 3., 4., 5.])

In [14]:
# np.arange
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [ ]:
# .reshape
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [24]:
# np.ones and np.zeros
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# np.random
np.random.random((2,3))

array([[0.89302201, 0.18210524, 0.44141559],
       [0.16400003, 0.71235538, 0.5553862 ]])

In [30]:
# np.linspace
np.linspace(-3, 7, 5)

array([-3. , -0.5,  2. ,  4.5,  7. ])

In [28]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### `Array Attributes`

In [52]:
a1 = np.arange(10)
a2 = np.arange(12, dtype = float).reshape(3,4)
a3 = np.arange(27).reshape(3,3,3)


In [38]:
#ndim
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [42]:
#shape
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(3, 3, 3)


In [48]:
#size
print(a1.size)
print(a2.size)
print(a3.size)

10
12
27


In [54]:
#itemsize
print(a1.itemsize, "bytes")
print(a2.itemsize, "bytes")
print(a3.itemsize, "bytes")

4 bytes
8 bytes
4 bytes


In [56]:
# dytpe
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


In [59]:
# Changing data type
# astype
print(a3.dtype)
a3.astype(np.int64)

int32


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]], dtype=int64)

### `Array Operations`

In [62]:
b1 = np.arange(10).reshape(2,5)
b2 = np.arange(10,20).reshape(2,5)

print(b1)
print()
print(b2)

[[0 1 2 3 4]
 [5 6 7 8 9]]

[[10 11 12 13 14]
 [15 16 17 18 19]]


In [ ]:
# Arithematic
# scalar
print(b1*2)
print()
print(b1+2)
print()
print(b1-2)
print()
print(b1/2)
print()
print(b1%2)
print()
print(b1**2)

[[ 0  2  4  6  8]
 [10 12 14 16 18]]

[[ 2  3  4  5  6]
 [ 7  8  9 10 11]]

[[-2 -1  0  1  2]
 [ 3  4  5  6  7]]

[[0.  0.5 1.  1.5 2. ]
 [2.5 3.  3.5 4.  4.5]]

[[0 1 0 1 0]
 [1 0 1 0 1]]

[[ 0  1  4  9 16]
 [25 36 49 64 81]]


In [70]:
# relational operations
print(b2 == 15)
print(b2 > 15)


[[False False False False False]
 [ True False False False False]]
[[False False False False False]
 [False  True  True  True  True]]


In [71]:
# vector ops
b1 + b2

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [81]:
# min / max / sum / prod
print(np.min(b2))
print(np.max(b2))

10
19


In [83]:
print(np.sum(b1))
print(np.prod(b1))


45
0


In [87]:
b1.min(axis = 1)

array([0, 5])

In [88]:
np.mean(b2)

14.5

In [90]:
np.std(b2)

2.8722813232690143

In [97]:
# dot product
b1 = b1.reshape(2,5)
b2 = b2.reshape(5,2)

print(b1)
print(b2)


[[0 1 2 3 4]
 [5 6 7 8 9]]
[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [98]:
np.dot(b1, b2)

array([[160, 170],
       [510, 545]])

In [101]:
# log and exponents
print(np.log(b2))
print("")
print(np.exp(b2))

[[2.30258509 2.39789527]
 [2.48490665 2.56494936]
 [2.63905733 2.7080502 ]
 [2.77258872 2.83321334]
 [2.89037176 2.94443898]]

[[2.20264658e+04 5.98741417e+04]
 [1.62754791e+05 4.42413392e+05]
 [1.20260428e+06 3.26901737e+06]
 [8.88611052e+06 2.41549528e+07]
 [6.56599691e+07 1.78482301e+08]]


In [110]:
# round / floor / ceil
x = (np.random.random((3,3))*100)



In [111]:
x

array([[42.43198125, 43.97557579, 18.6755177 ],
       [75.46399516, 87.13847249, 27.14298023],
       [69.22619252, 33.2801679 , 67.77706233]])

In [113]:
print(np.round(x))
print()
print(np.floor(x))
print()
print(np.ceil(x))

[[42. 44. 19.]
 [75. 87. 27.]
 [69. 33. 68.]]

[[42. 43. 18.]
 [75. 87. 27.]
 [69. 33. 67.]]

[[43. 44. 19.]
 [76. 88. 28.]
 [70. 34. 68.]]


### `Indexing and Slicing`

In [116]:
print(b1)
print()
print(b2)

[[0 1 2 3 4]
 [5 6 7 8 9]]

[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [120]:
b1[1] # 2nd row

array([5, 6, 7, 8, 9])

In [119]:
b2[2,1] # 15

15

In [124]:
b3 = np.arange(8).reshape(2,2,2)
b3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# indexing in 3d array
print(b3[1,1,0]) # 6
print(b3[0,0,0]) # 0
print(b3[1,0,0]) # 4


6
0
4


In [ ]:
# slicing a 2d array
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b[::2, 1::2] #type: ignore

array([[ 1,  3],
       [ 9, 11]])

In [156]:
b[1, ::3]

array([4, 7])

In [163]:
b[:2, 1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [165]:
# slicing a 3d array
b3 = np.arange(27).reshape(3,3,3)
b3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [177]:
b3[::2, 0, ::2]

array([[ 0,  2],
       [18, 20]])

In [166]:
b3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [169]:
b3[0,1, :]

array([3, 4, 5])

In [170]:
b3[1, :, 1]

array([10, 13, 16])

In [172]:
b3[2, 1:, 1:]

array([[22, 23],
       [25, 26]])

### `Iterating`

In [181]:
b1 = np.arange(10)
b1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [182]:
for i in b1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [186]:
print("1st loop")
for i in b2:
    print(i)
print()
print("2nd loop")
for i in np.nditer(b2):
    print(i)

1st loop
[10 11]
[12 13]
[14 15]
[16 17]
[18 19]

2nd loop
10
11
12
13
14
15
16
17
18
19


In [187]:
print("1st loop")
for i in b3:
    print(i)
print()
print("2nd loop")
for i in np.nditer(b3):
    print(i)


1st loop
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]

2nd loop
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### `Reshaping`

In [195]:
#transpose
print(b2.transpose())
#or
print(np.transpose(b2))
print(b2.T)

[[10 12 14 16 18]
 [11 13 15 17 19]]
[[10 12 14 16 18]
 [11 13 15 17 19]]
[[10 12 14 16 18]
 [11 13 15 17 19]]


In [196]:
b3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [198]:
# ravel()
# converts any array into 1D
b3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### `Stacking`
Requires the same shape

In [201]:
# horizontal stacking
x1 = np.arange(4).reshape(2,2)
x2 = np.arange(4, 8).reshape(2,2)

print(x1)
print(x2)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [203]:
np.hstack((x1,x2))

array([[0, 1, 4, 5],
       [2, 3, 6, 7]])

In [204]:
np.vstack((x1,x2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

### `Spliting`

In [205]:
#horizontal
np.hsplit(x1, 2)

[array([[0],
        [2]]),
 array([[1],
        [3]])]

In [208]:
#vertical
np.vsplit(x1, 2)

[array([[0, 1]]), array([[2, 3]])]